### ISSUE TITLE
I can't find it in jenkins plugins. where and how can i install this plugin to my jenkins ?

### ISSUE THREAD

**Issue by IamGabrielWu** [jenkinsci/tekton-client-plugin#56] opened 2021-02-12 12:25 UTC
I can't find it in jenkins plugins. where and how can i install this plugin to my jenkins ?

**Comment by jstrachan** [comment] 2021-03-23 11:23
its been released now, so you should be able to install it: http://archives.jenkins-ci.org/plugins/tekton-client/

**Comment by waveywaves** [comment] 2021-03-24 06:56
Closing as the issue is resolved

**Closed by waveywaves** 2021-03-24 06:56 UTC
